export const products = [
  {
    id: "1",
    category: "Scrunchies",
    name: "Scrunchie",
    img: "https://res.cloudinary.com/tinchoz8426/image/upload/v1636715435/img1_efa3lm.jpg",
    stock: 5,
    title: "Srunchie Aurora",
    description: "Scrunchie modelo Aurora, tenemos los mejores Scrunchies.",
    price: 345,
  },
  {
    id: "2",
    category: "Pañuelos",
    name: "Pañuelo",
    img: "https://res.cloudinary.com/tinchoz8426/image/upload/v1636715690/panuelo_ziz228.jpg",
    stock: 8,
    title: "Pañuelo Emma",
    description: "Pañuelo modelo Emma, no te podes perder nuestros pañuelos.",
    price: 456,
  },
  {
    id: "3",
    category: "Perfuminas",
    name: "Perfumina",
    img: "https://res.cloudinary.com/tinchoz8426/image/upload/v1636715510/perfumina_mirxbz.jpg",
    stock: 4,
    title: "Perfumina Lavanda",
    description: "Perfumina Lavanda, la fragancia mas fresca para tu ropa.",
    price: 765,
  },
];
